### ISSUE TITLE
YELLING

### ISSUE THREAD

**Issue by Sven65** [TheConceptionist/node-kitsu#1]
# LOUD YELLING

YELL
YELL
AAAAAAAA

I AM ANGRY

FIX MY ISSUE

AAAAAAAAAA

>:V

I AM YELL
YELL
YELL AT YOU
YOU CANNOT YELL BACK
BAD PRODUCT
BAD YELP

6/9 WOULD YELL

**Comment by TheConceptionist** [comment]
kthx
